spring:
  datasource:
    password: chile12
    url: jdbc:mysql://localhost:3306/bootdb?serverTimezone=UTC
    username: root
    

  jpa:
    hibernate:
      ddl-auto: update
      database-platform: org.hibernate.dialect.MySQL8Dialect

  security:
    oauth2:
      client:
        registration:
         google:
          clientId: #llenar
          clientSecret: #llenar
          scope:
           - email
           - profile